[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino

board_build.f_cpu = 160000000L
board_build.flash_mode = dio
board_build.ldscript = eagle.flash.4m1m.ld

monitor_speed = 115200
upload_speed = 921600

lib_deps = 
    adafruit/Adafruit SSD1306@^2.5.7
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit BusIO@^1.14.5
    bitbank2/PNGdec@^1.0.1

build_flags = 
    -D BEARSSL_SSL_BASIC
    -D NDEBUG
    -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY 
    -Os