[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino

board_build.f_cpu = 80000000L
board_build.ldscript = eagle.flash.4m1m.ld

monitor_speed = 115200

lib_deps = 
    crankyoldgit/IRremoteESP8266@^2.8.6
    adafruit/Adafruit SSD1306@^2.5.7
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit BusIO@^1.17.4